# coding: utf-8

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docspring
from docspring.models.combine_pdfs_data import CombinePdfsData  # noqa: E501
from docspring.rest import ApiException


class TestCombinePdfsData(unittest.TestCase):
    """CombinePdfsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCombinePdfsData(self):
        """Test CombinePdfsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = docspring.models.combine_pdfs_data.CombinePdfsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
