# coding: utf-8

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docspring
from docspring.models.list_submissions_response import ListSubmissionsResponse  # noqa: E501
from docspring.rest import ApiException


class TestListSubmissionsResponse(unittest.TestCase):
    """ListSubmissionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSubmissionsResponse(self):
        """Test ListSubmissionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = docspring.models.list_submissions_response.ListSubmissionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
