# coding: utf-8

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docspring
from docspring.models.folders_folder import FoldersFolder  # noqa: E501
from docspring.rest import ApiException


class TestFoldersFolder(unittest.TestCase):
    """FoldersFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFoldersFolder(self):
        """Test FoldersFolder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = docspring.models.folders_folder.FoldersFolder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
