# coding: utf-8

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docspring
from docspring.models.create_template_data1 import CreateTemplateData1  # noqa: E501
from docspring.rest import ApiException


class TestCreateTemplateData1(unittest.TestCase):
    """CreateTemplateData1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTemplateData1(self):
        """Test CreateTemplateData1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = docspring.models.create_template_data1.CreateTemplateData1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
