# coding: utf-8

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docspring
from docspring.models.templatesdesccached_upload_template_document import TemplatesdesccachedUploadTemplateDocument  # noqa: E501
from docspring.rest import ApiException


class TestTemplatesdesccachedUploadTemplateDocument(unittest.TestCase):
    """TemplatesdesccachedUploadTemplateDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplatesdesccachedUploadTemplateDocument(self):
        """Test TemplatesdesccachedUploadTemplateDocument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = docspring.models.templatesdesccached_upload_template_document.TemplatesdesccachedUploadTemplateDocument()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
