# coding: utf-8

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docspring
from docspring.models.templatesv2_template_document import Templatesv2TemplateDocument  # noqa: E501
from docspring.rest import ApiException


class TestTemplatesv2TemplateDocument(unittest.TestCase):
    """Templatesv2TemplateDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplatesv2TemplateDocument(self):
        """Test Templatesv2TemplateDocument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = docspring.models.templatesv2_template_document.Templatesv2TemplateDocument()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
