# coding: utf-8

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docspring
from docspring.models.create_template_from_upload_data import CreateTemplateFromUploadData  # noqa: E501
from docspring.rest import ApiException


class TestCreateTemplateFromUploadData(unittest.TestCase):
    """CreateTemplateFromUploadData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTemplateFromUploadData(self):
        """Test CreateTemplateFromUploadData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = docspring.models.create_template_from_upload_data.CreateTemplateFromUploadData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
