# coding: utf-8

# flake8: noqa

"""
    API v1

    DocSpring is a service that helps you fill out and sign PDF templates.  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.3.2"

# import apis into sdk package
from docspring.api.pdf_api import PDFApi

from .api.client import Client

# import ApiClient
from docspring.api_client import ApiClient
from docspring.configuration import Configuration
# import models into sdk package
from docspring.models.add_fields_data import AddFieldsData
from docspring.models.add_fields_template_response import AddFieldsTemplateResponse
from docspring.models.authentication_error import AuthenticationError
from docspring.models.authentication_success_response import AuthenticationSuccessResponse
from docspring.models.combine_pdfs_data import CombinePdfsData
from docspring.models.combined_submission import CombinedSubmission
from docspring.models.combined_submission_action import CombinedSubmissionAction
from docspring.models.combined_submission_data import CombinedSubmissionData
from docspring.models.copy_template_data import CopyTemplateData
from docspring.models.create_combined_submission_response import CreateCombinedSubmissionResponse
from docspring.models.create_custom_file_data import CreateCustomFileData
from docspring.models.create_custom_file_response import CreateCustomFileResponse
from docspring.models.create_folder_data import CreateFolderData
from docspring.models.create_html_template_data import CreateHtmlTemplateData
from docspring.models.create_submission_batch_response import CreateSubmissionBatchResponse
from docspring.models.create_submission_batch_submissions_response import CreateSubmissionBatchSubmissionsResponse
from docspring.models.create_submission_data_request_data import CreateSubmissionDataRequestData
from docspring.models.create_submission_data_request_token_response import CreateSubmissionDataRequestTokenResponse
from docspring.models.create_submission_data_request_token_response_token import CreateSubmissionDataRequestTokenResponseToken
from docspring.models.create_submission_response import CreateSubmissionResponse
from docspring.models.create_template_from_upload_data import CreateTemplateFromUploadData
from docspring.models.custom_file import CustomFile
from docspring.models.error import Error
from docspring.models.folder import Folder
from docspring.models.folders_folder import FoldersFolder
from docspring.models.html_template_data import HtmlTemplateData
from docspring.models.invalid_request import InvalidRequest
from docspring.models.list_submissions_response import ListSubmissionsResponse
from docspring.models.move_folder_data import MoveFolderData
from docspring.models.move_template_data import MoveTemplateData
from docspring.models.pending_template import PendingTemplate
from docspring.models.rename_folder_data import RenameFolderData
from docspring.models.submission import Submission
from docspring.models.submission_action import SubmissionAction
from docspring.models.submission_batch import SubmissionBatch
from docspring.models.submission_batch_data import SubmissionBatchData
from docspring.models.submission_data import SubmissionData
from docspring.models.submission_data_batch_request import SubmissionDataBatchRequest
from docspring.models.submission_data_request import SubmissionDataRequest
from docspring.models.template import Template
from docspring.models.template1 import Template1
from docspring.models.template1_defaults import Template1Defaults
from docspring.models.template_data import TemplateData
from docspring.models.templatestemplate_idadd_fields_fields import TemplatestemplateIdaddFieldsFields
from docspring.models.update_data_request_response import UpdateDataRequestResponse
from docspring.models.update_submission_data_request_data import UpdateSubmissionDataRequestData
from docspring.models.update_template_data import UpdateTemplateData
from docspring.models.update_template_response import UpdateTemplateResponse
from docspring.models.upload_template_data import UploadTemplateData
from docspring.models.upload_template_data_document import UploadTemplateDataDocument
from docspring.models.upload_template_data_document_metadata import UploadTemplateDataDocumentMetadata

